loggers=com.applv.sobes.wildflyapp
handlers=FILE

logger.com.applv.sobes.wildflyapp.level=INFO
logger.com.applv.sobes.wildflyapp.handlers=FILE
logger.com.applv.sobes.wildflyapp.useParentHandlers=true

handler.FILE=org.jboss.logmanager.handlers.PeriodicRotatingFileHandler
handler.FILE.level=INFO
handler.FILE.formatter=PATTERN
handler.FILE.properties=fileName,suffix,append
handler.FILE.fileName=${jboss.server.log.dir}/com.applv.sobes.wildflyapp.log
handler.FILE.suffix=.yyyy-MM-dd
handler.FILE.append=true

formatter.PATTERN=org.jboss.logmanager.formatters.PatternFormatter
formatter.PATTERN.properties=pattern
formatter.PATTERN.pattern=%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n